language: python
python:
    - "3.3"
    - "2.7"
    - "2.6"

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get install -qq python-numpy python-scipy

install: "pip install -r requirements.txt --use-mirrors"
 
script: nosetests

notifications:
    email:
        - cgates@umich.edu
